from ..unitquantity import UnitQuantity

rad: UnitQuantity
radian: UnitQuantity
radians: UnitQuantity
mrad: UnitQuantity
milliradian: UnitQuantity
urad: UnitQuantity
microradian: UnitQuantity
turn: UnitQuantity
revolution: UnitQuantity
cycle: UnitQuantity
turns: UnitQuantity
circle: UnitQuantity
circles: UnitQuantity
deg: UnitQuantity
degree: UnitQuantity
degrees: UnitQuantity
arcdeg: UnitQuantity
arcdegree: UnitQuantity
angular_degree: UnitQuantity
arcminute: UnitQuantity
arcmin: UnitQuantity
arc_minute: UnitQuantity
angular_minute: UnitQuantity
arcsecond: UnitQuantity
arcsec: UnitQuantity
arc_second: UnitQuantity
angular_second: UnitQuantity
grad: UnitQuantity
grade: UnitQuantity
degrees_north: UnitQuantity
degrees_N: UnitQuantity
degrees_east: UnitQuantity
degrees_E: UnitQuantity
degrees_west: UnitQuantity
degrees_W: UnitQuantity
degrees_true: UnitQuantity
degrees_T: UnitQuantity
sr: UnitQuantity
steradian: UnitQuantity
