from ..unitquantity import UnitQuantity, UnitInformation

bit: UnitInformation
B: UnitInformation
byte: UnitInformation
o: UnitInformation
octet: UnitInformation
kB: UnitInformation
kilobyte: UnitInformation
ko: UnitInformation
MB: UnitInformation
megabyte: UnitInformation
Mo: UnitInformation
GB: UnitInformation
gigabyte: UnitInformation
Go: UnitInformation
TB: UnitInformation
terabyte: UnitInformation
To: UnitInformation
PB: UnitInformation
petabyte: UnitInformation
Po: UnitInformation
EB: UnitInformation
exabyte: UnitInformation
Eo: UnitInformation
ZB: UnitInformation
zettabyte: UnitInformation
Zo: UnitInformation
YB: UnitInformation
yottabyte: UnitInformation
Yo: UnitInformation
Bd: UnitQuantity
baud: UnitQuantity
bps: UnitQuantity
KiB: UnitInformation
kibibyte: UnitInformation
Kio: UnitInformation
MiB: UnitInformation
mebibyte: UnitInformation
Mio: UnitInformation
GiB: UnitInformation
gibibyte: UnitInformation
Gio: UnitInformation
TiB: UnitInformation
tebibyte: UnitInformation
Tio: UnitInformation
PiB: UnitInformation
pebibyte: UnitInformation
Pio: UnitInformation
EiB: UnitInformation
exbibyte: UnitInformation
Eio: UnitInformation
ZiB: UnitInformation
zebibyte: UnitInformation
Zio: UnitInformation
YiB: UnitInformation
yobibyte: UnitInformation
Yio: UnitInformation
