"""
"""

from quantities.units.unitquantity import UnitLength

km = kilometer = kilometers = kilometre = kilometres = UnitLength('km')
m = meter = meters = metre = metres = UnitLength('m')
cm = centimeter = centimeters = centimetre = centimetres = UnitLength('cm', m/100)
mm = millimeter = millimeters = millimetre = millimetres = UnitLength('mm')
um = micron = microns = micrometer = micrometers = micrometre = micrometres = UnitLength('um')
nm = nanometer = nanometers = nanometre = nanometres = UnitLength('nm')
pm = picometer = picometers = picometre = picometres = UnitLength('pm')
angstrom = angstroms = UnitLength('angstroms')
fm = femtometer = femtometer = femtometre = femtometres = UnitLength('fm')
mi = mile = miles = international_mile = international_miles = UnitLength('mi')
yd = yard = yards = international_yard = international_yards = UnitLength('yd')
inch = inches = international_inch = international_inches = UnitLength('inch', 2.54*cm)
ft = foot = feet = international_foot = international_feet = UnitLength('ft', 12*inch)
mil = mils = UnitLength('mil')
pc = parsec = parsecs = UnitLength('parsec')
ly = light_year = light_years = UnitLength('light_year')
au = astronomical_unit = astronomical_units = UnitLength('au')
fermi = fermis = UnitLength('fermi')
nmi = nmile = nmiles = nautical_mile = nautical_miles = UnitLength('nautical_mile')
printers_point = printers_points = UnitLength('printers_point')
pica = picas = printers_pica = printers_picas = UnitLength('pica')
US_survey_foot = US_survey_feet = UnitLength('US_survey_foot', 1200./3937*m)
US_survey_yard = US_survey_yards = UnitLength('US_survey_yard')
US_survey_mile = US_survey_miles = UnitLength('US_survey_mile')
US_statute_mile = US_statute_miles = UnitLength('US_statute_mile')
rod = rods = pole = poles = perch = perches = UnitLength('rod', 16.5*US_survey_foot)
furlong = furlongs = UnitLength('furlong')
fathom = fathoms = UnitLength('fathom')
chain = chains = UnitLength('chain')
big_point = big_points = UnitLength('big_point')
barleycorn = barleycorns = UnitLength('barleycorn')
arpentlin = UnitLength('arpentlin')
