"""
"""

from quantities.units.unitquantities import length

km = kilometer = kilometers = kilometre = kilometres = length('km')
m = meter = meters = metre = metres = length('m')
cm = centimeter = centimeters = centimetre = centimetres = length('cm')
mm = millimeter = millimeters = millimetre = millimetres = length('mm')
um = micron = microns = micrometer = micrometers = micrometre = micrometres = length('um')
nm = nanometer = nanometers = nanometre = nanometres = length('nm')
pm = picometer = picometers = picometre = picometres = length('pm')
angstrom = angstroms = length('angstroms')
fm = femtometer = femtometer = femtometre = femtometres = length('fm')
mi = mile = miles = international_mile = international_miles = length('mi')
yd = yard = yards = international_yard = international_yards = length('yd')
ft = foot = feet = international_foot = international_feet = length('ft')
inch = inches = international_inch = international_inches = length('in')
mil = mils = length('mil')
pc = parsec = parsecs = length('parsec')
ly = light_year = light_years = length('light_year')
au = astronomical_unit = astronomical_units = length('au')
fermi = fermis = length('fermi')
nmi = nmile = nmiles = nautical_mile = nautical_miles = length('nautical_mile')
printers_point = printers_points = length('printers_point')
pica = picas = printers_pica = printers_picas = length('pica')
US_survey_foot = US_survey_feet = length('US_survey_foot')
US_survey_yard = US_survey_yards = length('US_survey_yard')
US_survey_mile = US_survey_miles = length('US_survey_mile')
US_statute_mile = US_statute_miles = length('US_statute_mile')
rod = rods = pole = poles = perch = perches = length('rod')
furlong = furlongs = length('furlong')
fathom = fathoms = length('fathom')
chain = chains = length('chain')
big_point = big_points = length('big_point')
barleycorn = barleycorns = length('barleycorn')
arpentlin = length('arpentlin')
