from ..unitquantity import UnitQuantity, UnitTime

s: UnitTime
sec: UnitTime
second: UnitTime
ks: UnitTime
kilosecond: UnitTime
Ms: UnitTime
megasecond: UnitTime
ms: UnitTime
millisecond: UnitTime
us: UnitTime
microsecond: UnitTime
ns: UnitTime
nanosecond: UnitTime
ps: UnitTime
picosecond: UnitTime
fs: UnitTime
femtosecond: UnitTime
attosecond: UnitTime
min: UnitTime
minute: UnitTime
h: UnitTime
hr: UnitTime
hour: UnitTime
d: UnitTime
day: UnitTime
week: UnitTime
fortnight: UnitTime
yr: UnitTime
year: UnitTime
tropical_year: UnitTime
a: UnitTime
month: UnitTime
shake: UnitTime
sidereal_day: UnitTime
sidereal_hour: UnitTime
sidereal_minute: UnitTime
sidereal_second: UnitTime
sidereal_year: UnitTime
sidereal_month: UnitTime
tropical_month: UnitTime
synodic_month: UnitTime
lunar_month: UnitTime
common_year: UnitTime
leap_year: UnitTime
Julian_year: UnitTime
Gregorian_year: UnitTime
millenium: UnitTime
eon: UnitTime
work_year: UnitQuantity
work_month: UnitQuantity
